# Site settings
title: A Local Business
description: Source . Negotiate . Trade . Sell
# baseurl: "https://topro.business" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Topro
user_description: Source . Negotiate . Trade . Sell
user_title: A Local Business
email: support@topro.business
twitter_username: topro_updates
gplus_username:  topro


# Google-analytics
google-analytics:
  id: "UA-122730651-1"

exclude: ['package.json', 'src' , 'node_modules']
